---
title: "dataload"
author: "yiyan Sun"
date: "2024-02-20"
output: html_document
---

```{r}
library(openair)
library(tidyverse)
library(openairmaps)
library(worldmet)

```

```{r}
aurn_meta <- importMeta(source = "aurn", all = TRUE)

london_rows <- aurn_meta[grep("London", aurn_meta$site, ignore.case = TRUE), ]

print(london_rows)

```

```{r}
networkMap(source = "aurn", control = "site_type")
```

```{r}
getMeta(lat = 53.3, lon = -0.3, returnMap = TRUE)
```


```{r}
getMeta()
```
```{r}
dublin_met <- importNOAA(code = "039690-99999", year = 2019)

# first few lines of data
dublin_met
```

```{r}
windRose(dublin_met)
```

```{r}
# import some air quality data and check the variables that exist

aq_2019 <- importAURN(site = "kc1", year = 2019)
names(aq_2019) # ws, wd, air_temp already exist from WRF model

# import some met data - default is London Heathrow
met_2019 <- importNOAA(year = 2019)

# merge the two data sets but not ws, wd, air_temp from aq data
aq_met <- left_join(
  select(aq_2019, -ws, -wd, -air_temp),
  met_2019,
  by = "date"
)

names(aq_met)
```

```{r}
windRose(mydata, type = "year", layout = c(4, 2))
```

```{r}
windRose(mydata, type = "pm10", layout = c(4, 1))
```

```{r}
pollutionRose(mydata, pollutant = "nox")
```
```{r}
pollutionRose(mydata,
  pollutant = "nox",
  type = "so2",
  layout = c(4, 1),
  key.position = "bottom"
)
```

```{r}
pollutionRose(mydata, pollutant = "nox", statistic = "prop.mean")
```

```{r}
pollutionRose(mydata,
  pollutant = "so2",
  normalise = TRUE,
  seg = 1,
  cols = "heat"
)
```

```{r}
## $example of comparing 2 met sites
## first we will make some new ws/wd data with a postive bias
mydata <- mutate(mydata,
  ws2 = ws + 2 * rnorm(nrow(mydata)) + 1,
  wd2 = wd + 30 * rnorm(nrow(mydata)) + 30
)

## need to correct negative wd
id <- which(mydata$wd2 < 0)
mydata$wd2[id] <- mydata$wd2[id] + 360

## results show postive bias in wd and ws
pollutionRose(mydata,
  ws = "ws",
  wd = "wd",
  ws2 = "ws2",
  wd2 = "wd2"
)
```

```{r}
## add some wd bias to some nighttime hours
id <- which(as.numeric(format(mydata$date, "%H")) %in% c(23, 1, 2, 3, 4, 5))
mydata$wd2[id] <- mydata$wd[id] + 30 * rnorm(length(id)) + 120
id <- which(mydata$wd2 < 0)
mydata$wd2[id] <- mydata$wd2[id] + 360

pollutionRose(mydata,
  ws = "ws", wd = "wd", ws2 = "ws2", wd2 = "wd2",
  breaks = c(-11, -2, -1, -0.5, 0.5, 1, 2, 11),
  cols = c("dodgerblue4", "white", "firebrick"),
  type = "daylight"
  )
```

